# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ab28ad039ab0dee4bdb60fa6eacdd77beaf432443dab689d396886e3781b661a432968c0f72a487ece002a429c9da739ebe71e5bce9bcfea0ab3e1b52a015004

test:
  secret_key_base: 408b39acaf20ee7cab07cc0cdc792164e532cef50c6703132da34449de71a10866da12c410b46b926785aa9f25a53f32aed2750117279d7b7dec6fbf8bdaec5f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
